### PR TITLE
Fix wiki links in config property descriptions

### LINKED ISSUE #444: Local links in fetched wiki is broken
## Description
ASF-ui fetched wiki for config params, but the local links in wiki text are broken like this:

```
http://127.0.0.1:1242/page/bot/botname/config#json-mapping
```

HTML may like this:

```html
<a href="#json-mapping">flags mapping</a>
```

This issue has nothing to do with the new fetching l10n wiki feature.

1 global config param and 3 bot config params are affected.

## Steps to reproduce
* go to any bot config window
* expand help text of `TradingPreferences`
* hover the `flags mapping` link and look the target

## Expected behavior
add missing configuration page link

## Current behavior
see description above

## Full snapshot
none

## Screenshots
none

## Additional information
none

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Fixes #444

### CODE REVIEW

File: src/utils/loadParameterDescriptions.js [hunk 1]
```diff
@@ -33,3 +36,14 @@ export default async function loadParameterDescriptions(version, locale) {
 
 	return descriptions;
 }
+
+export function fixWikiLinks(links, page) {
+	const locale = getLocaleForWiki();
```
Comment (Aareksio) [inline src/utils/loadParameterDescriptions.js]: Decide whether `locale` should be computed or passed as a parameter and stick to it.

Comment (MrBurrBurr) [reply src/utils/loadParameterDescriptions.js]: I opened #467 for that
