### PR TITLE
Handle required input types

### LINKED ISSUE #888: Unable to enter 2FA codes in ASF-ui
## Description
I switched from running ASF in a screen instance to a Docker with the IPC+UI. I've setup a bot but it can't start because it cannot login without the 2FA code.

Am I doing something wrong here or isn't this supported? Is there a workaround?

## Steps to reproduce
- Use the UI to create a bot with name, Steam username & Steam password
- Start newly created bot

## Expected behavior
The UI should ask for me to enter a 2FA code, similair to the 'oldschool' command line.

## Current behavior
Nothing is asked and the UI gives an error, the bot is stopped.

## Additional information

Using Docker w/ Portainer. Config folder mapped to folder on the host.

### Full log

```
[21:45:18] INFO ASF > Start() IPC server ready!
[21:45:19] INFO Bot1 > Start() Starting...
[21:45:19] INFO Bot1 > Connect() Connecting...
[21:45:20] INFO Bot1 > OnConnected() Connected to Steam!
[21:45:20] INFO Bot1 > OnConnected() Logging in...
[21:45:21] INFO Bot1 > Stop() Stopping...
```

### IPC.config
```json
{
	"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:1242"
			}
		}
	}
}
```

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #888

### CODE REVIEW

File: src/utils/getUserInputType.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// Todo: Read EUserInputType from api
```
Comment (JustArchi) [inline src/utils/getUserInputType.js:1]: You're adding yourself more work in the future. You should never hardcode any ASF types, "todo for future" doesn't cut it, this can break at any single point in the future and you **won't know about it** until users tell you that the UI doesn't work anymore.

File: src/views/modals/BotInput.vue [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+        if (field.getAttribute('type') === 'password') field.setAttribute('type', 'text');
+        else field.setAttribute('type', 'password');
+      },
+      async submit() {
+        if (this.submitting) return;
+
+        this.submitting = true;
+
+        try {
+          await this.$http.post(`bot/${this.bot.name}/input`, { type: this.bot.requiredInput, value: this.code });
```
Comment (JustArchi) [inline src/views/modals/BotInput.vue:71]: How is this guarded against `requiredInput` changing in the middle of user entering it? How is this guarded against verifying that the input that user is entering is still required here?

Comment (MrBurrBurr) [reply src/views/modals/BotInput.vue:71]: Hm. I think I might not understand it quiet well. How can the `requiredInput` change in that case? And what could we do to handle such a situation?

File: src/utils/getUserInputType.js (hunk 1 above)
Comment (MrBurrBurr) [reply src/utils/getUserInputType.js:1]: You are right and I agree with you, but I am in the situation that I would like to wait for #1022 to be merged so I can easily fetch the schema for `EUserInputType`. AFAIK its not easily possible right now. We also got https://github.com/JustArchiNET/ASF-ui/blob/master/src/utils/getCountryCode.js that will need to adjust.

File: src/views/modals/BotInput.vue (hunk 2 above)
Comment (JustArchi) [reply src/views/modals/BotInput.vue:71]: > How can the requiredInput change in that case?

User might use `input` command in the console between you displaying him the window to enter the details AND him inputting them and confirming.

> And what could we do to handle such a situation?

Verify if the required input is the same as the one when you displayed the window at the moment you're about to call API endpoint.

File: src/utils/getUserInputType.js (hunk 1 above)
Comment (JustArchi) [reply src/utils/getUserInputType.js:1]: Then maybe it's worth it to finish #1022 first before adding more code that you're guaranteed to rewrite the moment it's in. I'm not a fan of coding something which is already **doomed** to be replaced in the future, it's entirely counter-productive to write something that you're going to trash in the next second.

Comment (MrBurrBurr) [reply src/utils/getUserInputType.js:1]: I agree, it's worth finishing #1022 but I don't see that happening in the near future. So in the meantime we could profit from this new feature, even though it will be rewritten at some point and there is a minimal chance it might break.
